service: shorter-urls

frameworkVersion: ">=1.1.0 <2.0.0"

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - ${self:provider.stage}
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    DYNAMODB_LOGS: ${self:service}-${opt:stage, self:provider.stage}-logs
    ADMIN_KEY: "test" 
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  create:
    handler: shorturl/create.create
    events:
      - http:
          path: shorturl
          method: post
          cors: true

  list:
    handler: shorturl/list.list
    events:
      - http:
          path: shorturl
          method: get
          cors: true

  get:
    handler: shorturl/get.get
    events:
      - http:
          path: shorturl/{id}
          method: get
          cors: true

  delete:
    handler: shorturl/delete.delete
    events:
      - http:
          path: shorturl/{id}
          method: delete
          cors: true

resources:
  Resources:
    ShorturlDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
